### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by anton-avramchuk** [dsindex/syntaxnet#9]
I'm trying to train UD_English and I want to see output like [this](https://github.com/dsindex/syntaxnet/tree/master/English). After transform `context.pbtxt` like [context from English](https://github.com/dsindex/syntaxnet/blob/master/English/context.pbtxt) and run `./train.sh -v -v` I see error:
`
INFO:tensorflow:Training...
INFO:tensorflow:Building training network with parameters: feature_sizes: [] domain_sizes: []
Traceback (most recent call last):
  File "/home/anton/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 303, in <module>
    tf.app.run()
  File "/home/anton/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/anton/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 299, in main
    Train(sess, num_actions, feature_sizes, domain_sizes, embedding_dims)
  File "/home/anton/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 212, in Train
    corpus_name=corpus_name)
  File "/home/anton/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/graph_builder.py", line 512, in AddTraining
    nodes.update(self._AddGoldReader(task_context, batch_size, corpus_name))
  File "/home/anton/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/graph_builder.py", line 381, in _AddGoldReader
    arg_prefix=self._arg_prefix))
  File "/home/anton/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/ops/gen_parser_ops.py", line 321, in gold_parse_reader
    arg_prefix=arg_prefix, name=name)
  File "/home/anton/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 627, in apply_op
    (key, op_type_name, attr_value.i, attr_def.minimum))
ValueError: Attr 'feature_size' of 'GoldParseReader' Op passed 0 less than minimum 1.
`

[context2.txt](https://github.com/dsindex/syntaxnet/files/529055/context2.txt)

**Comment by dsindex** [comment]
@zizoo 

hello zizoo~ 

'English' directory(a model of Parsey's cousin) was downloaded from 'http://download.tensorflow.org/models/parsey_universal/<language>.zip' ( https://github.com/tensorflow/models/blob/master/syntaxnet/universal.md )

you can see that there are tokenizer and morpher model(params) with tagger and parser.
unfortunately, at least now, it is not possible to train tokenizer and morpher model from UD_English because the code is not provided yet.

but you can train tagger and parser by using `train.sh`.

**Comment by anton-avramchuk** [comment]
Thank you!
